### ISSUE TITLE
error when click on orders in admin panel

### ISSUE THREAD

**Issue by miladazhdehnia** [raylight75/cms#10] opened 2019-02-20 14:43 UTC
hello
when clicking on orders in admin panel its show me this:
"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?
`$methodClass = get_class($this->relation);
            switch ($methodClass) {
                case 'Illuminate\Database\Eloquent\Relations\BelongsToMany':
 
                    $old_data = $this->relation->get()->modelKeys();
                    $new_data = explode($this->serialization_sep, $data);
 
                    $this->relation->detach($old_data);
 
                    if ($data=='') {
                        continue;
                    }
 
                    if (is_callable($this->extra_attributes)) {
                        $callable = $this->extra_attributes;
                        foreach ($new_data as $d) {
                            $this->relation->attach($d, $callable($d));
                        }
                    } elseif (is_array($this->extra_attributes)) {
                        $this->relation->attach($new_data, $this->extra_attributes);
                    }
 
                    break;
                case 'Illuminate\Database\Eloquent\Relations\HasOne':`

**Comment by raylight75** [comment] 2019-02-21 07:34
Can you provide more details, I can't reproduce such error. Have you updated all packages and perform composer upadte?

**Comment by raylight75** [comment] 2019-02-27 08:20
Without additional information, I will close this issue

**Closed by raylight75** 2019-02-27 08:20 UTC

**Comment by uniquechukwuma** [comment] 2019-05-18 13:38
Please am getting this error as well
